version: '3.9'

services:
  postgres:
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=1606
      - POSTGRES_USER=admin
      - PGDATA="/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    image: postgres:alpine3.18

  firstclass:
    build: /
    restart: always
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB=postgres
      - POSTGRES_DB_PORT=5432
      - STORAGE_SERVICE_IMPL=postgres
      - LOG_MODE=dev


volumes:
  postgres-data: